[k8s_master]
master01    ansible_host=ec2-13-221-20-181.compute-1.amazonaws.com    ansible_user=ubuntu

[k8s_workers]
worker-red  ansible_host=ec2-34-226-202-200.compute-1.amazonaws.com   ansible_user=ubuntu
worker-blue ansible_host=ec2-54-91-226-9.compute-1.amazonaws.com      ansible_user=ubuntu

[k8s_cluster:children]
k8s_master
k8s_workers

[k8s_cluster:vars]
ansible_ssh_private_key_file=~/demo.pem
